name: Build

on:
  workflow_dispatch:

jobs:
  build-goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup pnpm
        run: |
        wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -
        source /root/.bashrc

      - name: Build
        run: ./answer build --with conector-wechat@1.0.0=${{ github.workspace }}/connector-wechat
